version: "3"
services:

  db:
    image: mongo
    container_name: db
    ports: 
      - "27017:27017"
    volumes: 
      - "data:/data/db"

  chatapp:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      - "db"

volumes:
  data:
